Update of the dependency version.
Without the correct dependencies, the following error is obtained:

Java2WSDL it.smc.despar.addressbook.service.http.ContactServiceSoap
- The class com.liferay.portal.kernel.portlet.LiferayPortletRequest does not contain a default constructor, which is a requirement for a bean class.  The class cannot be converted into an xml schema type.  An xml schema anyType will be used to define this class in the wsdl file.
 java.lang.NoClassDefFoundError: javax/portlet/MimeResponse$Copy
     at java.lang.Class.getDeclaredMethods0(Native Method)
     at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
     at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
     at java.lang.Class.getMethod0(Class.java:3018)
     at java.lang.Class.getMethod(Class.java:1784)